//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Request parameters for 
/// Operation: GET /api/document_types/
/// </summary>
public partial class DocumentTypesListRequest : BaseRequest
{
  /// <summary>
  /// full_perms
  /// </summary>
  [JsonPropertyName("full_perms")]
  public bool? FullPerms { get; set; }

  /// <summary>
  /// id
  /// </summary>
  [JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// Multiple values may be separated by commas.
  /// </summary>
  [JsonPropertyName("id__in")]
  public List<int>? IdIn { get; set; }

  /// <summary>
  /// name__icontains
  /// </summary>
  [JsonPropertyName("name__icontains")]
  public string? NameIcontains { get; set; }

  /// <summary>
  /// name__iendswith
  /// </summary>
  [JsonPropertyName("name__iendswith")]
  public string? NameIendswith { get; set; }

  /// <summary>
  /// name__iexact
  /// </summary>
  [JsonPropertyName("name__iexact")]
  public string? NameIexact { get; set; }

  /// <summary>
  /// name__istartswith
  /// </summary>
  [JsonPropertyName("name__istartswith")]
  public string? NameIstartswith { get; set; }

  /// <summary>
  /// Which field to use when ordering the results.
  /// </summary>
  [JsonPropertyName("ordering")]
  public string? Ordering { get; set; }

  /// <summary>
  /// A page number within the paginated result set.
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// Number of results to return per page.
  /// </summary>
  [JsonPropertyName("page_size")]
  public int? PageSize { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (FullPerms != null)
      queryParams["full_perms"] = FullPerms;
    if (Id != null)
      queryParams["id"] = Id;
    if (IdIn != null)
      queryParams["id__in"] = QueryStringExtensions.Join(IdIn, ",");
    if (NameIcontains != null)
      queryParams["name__icontains"] = NameIcontains;
    if (NameIendswith != null)
      queryParams["name__iendswith"] = NameIendswith;
    if (NameIexact != null)
      queryParams["name__iexact"] = NameIexact;
    if (NameIstartswith != null)
      queryParams["name__istartswith"] = NameIstartswith;
    if (Ordering != null)
      queryParams["ordering"] = Ordering;
    if (Page != null)
      queryParams["page"] = Page;
    if (PageSize != null)
      queryParams["page_size"] = PageSize;

    return queryParams.ToQueryString();
  }
}
