//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for bulk_edit_objects operations
/// </summary>
public partial interface IBulkEditObjectsClient
{
  /// <summary>
  /// 
  /// Operation: POST /api/bulk_edit_objects/
  /// </summary>
  Task<BulkEditResult> BulkEditObjectsAsync(Apigen.PaperlessNgx.Models.BulkEditObjectsRequest bulkEditObjectsRequest, CancellationToken cancellationToken = default);

}
