//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for correspondents operations
/// </summary>
public partial interface ICorrespondentsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/correspondents/
  /// </summary>
  Task<PaginatedCorrespondentList> ListAsync(CorrespondentsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/correspondents/
  /// </summary>
  Task<Correspondent> CreateAsync(Apigen.PaperlessNgx.Models.CorrespondentRequest correspondentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/correspondents/{id}/
  /// </summary>
  Task<Correspondent> GetAsync(int id, CorrespondentsRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/correspondents/{id}/
  /// </summary>
  Task<Correspondent> UpdateAsync(int id, Apigen.PaperlessNgx.Models.CorrespondentRequest correspondentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/correspondents/{id}/
  /// </summary>
  Task<Correspondent> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedCorrespondentRequest patchedCorrespondentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/correspondents/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
