//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for custom_fields operations
/// </summary>
public partial interface ICustomFieldsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/custom_fields/
  /// </summary>
  Task<PaginatedCustomFieldList> ListAsync(CustomFieldsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/custom_fields/
  /// </summary>
  Task<CustomField> CreateAsync(Apigen.PaperlessNgx.Models.CustomFieldRequest customFieldRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/custom_fields/{id}/
  /// </summary>
  Task<CustomField> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/custom_fields/{id}/
  /// </summary>
  Task<CustomField> UpdateAsync(int id, Apigen.PaperlessNgx.Models.CustomFieldRequest customFieldRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/custom_fields/{id}/
  /// </summary>
  Task<CustomField> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedCustomFieldRequest patchedCustomFieldRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/custom_fields/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
