//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for documents operations
/// </summary>
public partial interface IDocumentsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/documents/
  /// </summary>
  Task<PaginatedDocumentList> ListAsync(DocumentsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/
  /// </summary>
  Task<Document> GetAsync(int id, DocumentsRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/documents/{id}/
  /// </summary>
  Task<Document> UpdateAsync(int id, Apigen.PaperlessNgx.Models.DocumentRequest documentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/documents/{id}/
  /// </summary>
  Task<Document> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedDocumentRequest patchedDocumentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/documents/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/ai_suggestions/
  /// </summary>
  Task<AISuggestions> AiSuggestionsRetrieveAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/download/
  /// </summary>
  Task<Stream> DownloadAsync(int id, DownloadRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/{id}/email/
  /// </summary>
  Task<EmailDocumentResponse> EmailDocumentAsync(int id, Apigen.PaperlessNgx.Models.EmailDocumentRequest emailDocumentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/history/
  /// </summary>
  Task<PaginatedLogEntryList> HistoryListAsync(int id, DocumentsHistoryListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/metadata/
  /// </summary>
  Task<Metadata> GetMetadataAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/notes/
  /// </summary>
  Task<List<Note>> NotesListAsync(int id, DocumentsNotesListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/{id}/notes/
  /// </summary>
  Task<List<Note>> NotesCreateAsync(int id, Apigen.PaperlessNgx.Models.NoteCreateRequest noteCreateRequest, DocumentsNotesCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/documents/{id}/notes/
  /// </summary>
  Task<List<Note>> DeleteNoteAsync(int id, DeleteNoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/preview/
  /// </summary>
  Task<Stream> PreviewAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/root/
  /// </summary>
  Task<DocumentRootResponse> RootAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/share_links/
  /// </summary>
  Task<JsonElement> ShareLinksAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/suggestions/
  /// </summary>
  Task<Suggestions> SuggestionsRetrieveAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/{id}/thumb/
  /// </summary>
  Task<Stream> ThumbnailAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/{id}/update_version/
  /// </summary>
  Task<string> UpdateVersionAsync(int id, Apigen.PaperlessNgx.Models.DocumentVersionRequest documentVersionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/documents/{id}/versions/{version_id}/
  /// </summary>
  Task<UpdateDocumentVersionLabelResult> UpdateVersionLabelAsync(int id, int versionId, Apigen.PaperlessNgx.Models.PatchedDocumentVersionLabelRequest patchedDocumentVersionLabelRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/documents/{id}/versions/{version_id}/
  /// </summary>
  Task DeleteVersionAsync(int id, int versionId, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/bulk_download/
  /// </summary>
  Task<Stream> BulkDownloadAsync(Apigen.PaperlessNgx.Models.BulkDownloadRequest bulkDownloadRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/bulk_edit/
  /// </summary>
  Task<BulkEditDocumentsResult> BulkEditAsync(Apigen.PaperlessNgx.Models.BulkEditRequest bulkEditRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/chat/
  /// </summary>
  Task<ChatStreaming> ChatCreateAsync(Apigen.PaperlessNgx.Models.ChatStreamingRequest chatStreamingRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/delete/
  /// </summary>
  Task<DeleteDocumentsResult> BulkDeleteAsync(Apigen.PaperlessNgx.Models.DeleteDocumentsRequest deleteDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/edit_pdf/
  /// </summary>
  Task<EditPdfDocumentsResult> EditPdfAsync(Apigen.PaperlessNgx.Models.EditPdfDocumentsRequest editPdfDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/email/
  /// </summary>
  Task<EmailDocumentResponse> EmailAsync(Apigen.PaperlessNgx.Models.EmailRequest emailRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/merge/
  /// </summary>
  Task<MergeDocumentsResult> MergeAsync(Apigen.PaperlessNgx.Models.MergeDocumentsRequest mergeDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/merge_as_versions/
  /// </summary>
  Task<MergeDocumentsAsVersionsResult> MergeAsVersionsAsync(Apigen.PaperlessNgx.Models.MergeDocumentsAsVersionsRequest mergeDocumentsAsVersionsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/documents/next_asn/
  /// </summary>
  Task<int> GetNextAsnAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/post_document/
  /// </summary>
  Task<string> PostDocumentCreateAsync(Apigen.PaperlessNgx.Models.PostDocumentRequest postDocumentRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/remove_password/
  /// </summary>
  Task<RemovePasswordDocumentsResult> RemovePasswordAsync(Apigen.PaperlessNgx.Models.RemovePasswordDocumentsRequest removePasswordDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/reprocess/
  /// </summary>
  Task<ReprocessDocumentsResult> ReprocessAsync(Apigen.PaperlessNgx.Models.ReprocessDocumentsRequest reprocessDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/rotate/
  /// </summary>
  Task<RotateDocumentsResult> RotateAsync(Apigen.PaperlessNgx.Models.RotateDocumentsRequest rotateDocumentsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/documents/selection_data/
  /// </summary>
  Task<SelectionData> GetSelectionDataAsync(Apigen.PaperlessNgx.Models.DocumentListRequest documentListRequest, CancellationToken cancellationToken = default);

}
