//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for document_types operations
/// </summary>
public partial interface IDocumentTypesClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/document_types/
  /// </summary>
  Task<PaginatedDocumentTypeList> ListAsync(DocumentTypesListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/document_types/
  /// </summary>
  Task<DocumentType> CreateAsync(Apigen.PaperlessNgx.Models.DocumentTypeRequest documentTypeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/document_types/{id}/
  /// </summary>
  Task<DocumentType> GetAsync(int id, DocumentTypesRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/document_types/{id}/
  /// </summary>
  Task<DocumentType> UpdateAsync(int id, Apigen.PaperlessNgx.Models.DocumentTypeRequest documentTypeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/document_types/{id}/
  /// </summary>
  Task<DocumentType> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedDocumentTypeRequest patchedDocumentTypeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/document_types/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
