//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for groups operations
/// </summary>
public partial interface IGroupsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/groups/
  /// </summary>
  Task<PaginatedGroupList> ListAsync(GroupsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/groups/
  /// </summary>
  Task<Group> CreateAsync(Apigen.PaperlessNgx.Models.GroupRequest groupRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/groups/{id}/
  /// </summary>
  Task<Group> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/groups/{id}/
  /// </summary>
  Task<Group> UpdateAsync(int id, Apigen.PaperlessNgx.Models.GroupRequest groupRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/groups/{id}/
  /// </summary>
  Task<Group> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedGroupRequest patchedGroupRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/groups/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
