//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for mail_accounts operations
/// </summary>
public partial interface IMailAccountsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/mail_accounts/
  /// </summary>
  Task<PaginatedMailAccountList> ListAsync(MailAccountsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/mail_accounts/
  /// </summary>
  Task<MailAccount> CreateAsync(Apigen.PaperlessNgx.Models.MailAccountRequest mailAccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/mail_accounts/{id}/
  /// </summary>
  Task<MailAccount> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/mail_accounts/{id}/
  /// </summary>
  Task<MailAccount> UpdateAsync(int id, Apigen.PaperlessNgx.Models.MailAccountRequest mailAccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/mail_accounts/{id}/
  /// </summary>
  Task<MailAccount> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedMailAccountRequest patchedMailAccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/mail_accounts/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/mail_accounts/{id}/process/
  /// </summary>
  Task<MailAccountProcessResponse> ProcessAsync(int id, Apigen.PaperlessNgx.Models.MailAccountRequest mailAccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/mail_accounts/test/
  /// </summary>
  Task<MailAccountTestResponse> TestAsync(Apigen.PaperlessNgx.Models.MailAccountRequest mailAccountRequest, CancellationToken cancellationToken = default);

}
