//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for mail_rules operations
/// </summary>
public partial interface IMailRulesClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/mail_rules/
  /// </summary>
  Task<PaginatedMailRuleList> ListAsync(MailRulesListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/mail_rules/
  /// </summary>
  Task<MailRule> CreateAsync(Apigen.PaperlessNgx.Models.MailRuleRequest mailRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/mail_rules/{id}/
  /// </summary>
  Task<MailRule> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/mail_rules/{id}/
  /// </summary>
  Task<MailRule> UpdateAsync(int id, Apigen.PaperlessNgx.Models.MailRuleRequest mailRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/mail_rules/{id}/
  /// </summary>
  Task<MailRule> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedMailRuleRequest patchedMailRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/mail_rules/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
