//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for profile operations
/// </summary>
public partial interface IProfileClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/profile/
  /// </summary>
  Task<Profile> ListAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/profile/
  /// </summary>
  Task<Profile> PartialUpdateAsync(Apigen.PaperlessNgx.Models.PatchedProfileRequest patchedProfileRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/profile/disconnect_social_account/
  /// </summary>
  Task<int> DisconnectSocialAccountCreateAsync(Apigen.PaperlessNgx.Models.ProfileDisconnectSocialAccountCreateRequest profileDisconnectSocialAccountCreateRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/profile/generate_auth_token/
  /// </summary>
  Task<string> GenerateAuthTokenCreateAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/profile/social_account_providers/
  /// </summary>
  Task<JsonElement> SocialAccountProvidersRetrieveAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/profile/totp/
  /// </summary>
  Task<JsonElement> TotpRetrieveAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/profile/totp/
  /// </summary>
  Task<JsonElement> TotpCreateAsync(Apigen.PaperlessNgx.Models.ProfileTotpCreateRequest profileTotpCreateRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/profile/totp/
  /// </summary>
  Task<bool> DisableTotpAsync(CancellationToken cancellationToken = default);

}
