//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for processed_mail operations
/// </summary>
public partial interface IProcessedMailClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/processed_mail/
  /// </summary>
  Task<PaginatedProcessedMailList> ListAsync(ProcessedMailListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/processed_mail/{id}/
  /// </summary>
  Task<ProcessedMail> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/processed_mail/bulk_delete/
  /// </summary>
  Task<BulkDeleteMailResponse> BulkDeleteAsync(Apigen.PaperlessNgx.Models.BulkDeleteMailRequest bulkDeleteMailRequest, CancellationToken cancellationToken = default);

}
