//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for saved_views operations
/// </summary>
public partial interface ISavedViewsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/saved_views/
  /// </summary>
  Task<PaginatedSavedViewList> ListAsync(SavedViewsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/saved_views/
  /// </summary>
  Task<SavedView> CreateAsync(Apigen.PaperlessNgx.Models.SavedViewRequest savedViewRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/saved_views/{id}/
  /// </summary>
  Task<SavedView> GetAsync(int id, SavedViewsRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/saved_views/{id}/
  /// </summary>
  Task<SavedView> UpdateAsync(int id, Apigen.PaperlessNgx.Models.SavedViewRequest savedViewRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/saved_views/{id}/
  /// </summary>
  Task<SavedView> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedSavedViewRequest patchedSavedViewRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/saved_views/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
