//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for share_links operations
/// </summary>
public partial interface IShareLinksClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/share_links/
  /// </summary>
  Task<PaginatedShareLinkList> ListAsync(ShareLinksListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/share_links/
  /// </summary>
  Task<ShareLink> CreateAsync(Apigen.PaperlessNgx.Models.ShareLinkRequest shareLinkRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/share_links/{id}/
  /// </summary>
  Task<ShareLink> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/share_links/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
