//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for storage_paths operations
/// </summary>
public partial interface IStoragePathsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/storage_paths/
  /// </summary>
  Task<PaginatedStoragePathList> ListAsync(StoragePathsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/storage_paths/
  /// </summary>
  Task<StoragePath> CreateAsync(Apigen.PaperlessNgx.Models.StoragePathRequest storagePathRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/storage_paths/{id}/
  /// </summary>
  Task<StoragePath> GetAsync(int id, StoragePathsRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/storage_paths/{id}/
  /// </summary>
  Task<StoragePath> UpdateAsync(int id, Apigen.PaperlessNgx.Models.StoragePathRequest storagePathRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/storage_paths/{id}/
  /// </summary>
  Task<StoragePath> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedStoragePathRequest patchedStoragePathRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/storage_paths/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/storage_paths/test/
  /// </summary>
  Task<string> TestAsync(Apigen.PaperlessNgx.Models.StoragePathTestRequest storagePathTestRequest, CancellationToken cancellationToken = default);

}
