//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for tags operations
/// </summary>
public partial interface ITagsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/tags/
  /// </summary>
  Task<PaginatedTagList> ListAsync(TagsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/tags/
  /// </summary>
  Task<Tag> CreateAsync(Apigen.PaperlessNgx.Models.TagRequest tagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/tags/{id}/
  /// </summary>
  Task<Tag> GetAsync(int id, TagsRetrieveRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/tags/{id}/
  /// </summary>
  Task<Tag> UpdateAsync(int id, Apigen.PaperlessNgx.Models.TagRequest tagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/tags/{id}/
  /// </summary>
  Task<Tag> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedTagRequest patchedTagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/tags/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
