//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for tasks operations
/// </summary>
public partial interface ITasksClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/tasks/
  /// </summary>
  Task<PaginatedPaperlessTaskList> ListAsync(TasksListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/tasks/{id}/
  /// </summary>
  Task<PaperlessTask> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/tasks/acknowledge/
  /// </summary>
  Task<AcknowledgeTasksResult> AcknowledgeAsync(Apigen.PaperlessNgx.Models.AcknowledgeTasksRequest acknowledgeTasksRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/tasks/active/
  /// </summary>
  Task<List<PaperlessTask>> ActiveListAsync(TasksActiveListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/tasks/run/
  /// </summary>
  Task<RunTask> RunAsync(Apigen.PaperlessNgx.Models.RunTaskRequest runTaskRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/tasks/status_counts/
  /// </summary>
  Task<TaskStatusCounts> GetStatusCountsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/tasks/summary/
  /// </summary>
  Task<List<TaskSummary>> SummaryListAsync(TasksSummaryListRequest? request = null, CancellationToken cancellationToken = default);

}
