//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for trash operations
/// </summary>
public partial interface ITrashClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/trash/
  /// </summary>
  Task GetAsync(TrashListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/trash/
  /// </summary>
  Task CreateAsync(Apigen.PaperlessNgx.Models.TrashRequest trashRequest, CancellationToken cancellationToken = default);

}
