//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for users operations
/// </summary>
public partial interface IUsersClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/users/
  /// </summary>
  Task<PaginatedUserList> ListAsync(UsersListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/users/
  /// </summary>
  Task<User> CreateAsync(Apigen.PaperlessNgx.Models.UserRequest userRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/users/{id}/
  /// </summary>
  Task<User> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/users/{id}/
  /// </summary>
  Task<User> UpdateAsync(int id, Apigen.PaperlessNgx.Models.UserRequest userRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/users/{id}/
  /// </summary>
  Task<User> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.PatchedUserRequest patchedUserRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/users/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/users/{id}/deactivate_totp/
  /// </summary>
  Task<bool> DeactivateTotpAsync(int id, CancellationToken cancellationToken = default);

}
