//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.PaperlessNgx.Models;

#nullable enable

namespace Apigen.PaperlessNgx.Client;

/// <summary>
/// Interface for workflow_actions operations
/// </summary>
public partial interface IWorkflowActionsClient
{
  /// <summary>
  /// 
  /// Operation: GET /api/workflow_actions/
  /// </summary>
  Task<PaginatedWorkflowActionList> ListAsync(WorkflowActionsListRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: POST /api/workflow_actions/
  /// </summary>
  Task<WorkflowAction> CreateAsync(Apigen.PaperlessNgx.Models.WorkflowActionRequest workflowActionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: GET /api/workflow_actions/{id}/
  /// </summary>
  Task<WorkflowAction> GetAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PUT /api/workflow_actions/{id}/
  /// </summary>
  Task<WorkflowAction> UpdateAsync(int id, Apigen.PaperlessNgx.Models.WorkflowActionRequest workflowActionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: PATCH /api/workflow_actions/{id}/
  /// </summary>
  Task<WorkflowAction> PartialUpdateAsync(int id, Apigen.PaperlessNgx.Models.WorkflowActionRequest workflowActionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /api/workflow_actions/{id}/
  /// </summary>
  Task DeleteAsync(int id, CancellationToken cancellationToken = default);

}
