//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
#nullable enable

using System.Net.Http;
using System.Text.Json;
using Apigen.PaperlessNgx.Models;

namespace Apigen.PaperlessNgx.Client;

internal static class MultipartContentExtensions
{
  public static MultipartFormDataContent ToMultipartContent(this Apigen.PaperlessNgx.Models.DocumentVersionRequest documentVersionRequest)
  {
    MultipartFormDataContent content = new();
    content.Add(new ByteArrayContent(documentVersionRequest.Document), "document", "document.bin");
    if (documentVersionRequest.VersionLabel != null)
      content.Add(new StringContent(documentVersionRequest.VersionLabel), "version_label");
    return content;
  }
  public static MultipartFormDataContent ToMultipartContent(this Apigen.PaperlessNgx.Models.PostDocumentRequest postDocumentRequest)
  {
    MultipartFormDataContent content = new();
    if (postDocumentRequest.Created != null)
      content.Add(new StringContent(postDocumentRequest.Created.Value.ToString("O")), "created");
    content.Add(new ByteArrayContent(postDocumentRequest.Document), "document", "document.bin");
    if (postDocumentRequest.Title != null)
      content.Add(new StringContent(postDocumentRequest.Title), "title");
    if (postDocumentRequest.Correspondent != null)
      content.Add(new StringContent(postDocumentRequest.Correspondent.Value.ToString()), "correspondent");
    if (postDocumentRequest.DocumentType != null)
      content.Add(new StringContent(postDocumentRequest.DocumentType.Value.ToString()), "document_type");
    if (postDocumentRequest.StoragePath != null)
      content.Add(new StringContent(postDocumentRequest.StoragePath.Value.ToString()), "storage_path");
    if (postDocumentRequest.Tags != null)
      content.Add(new StringContent(JsonSerializer.Serialize(postDocumentRequest.Tags, JsonConfig.Default)), "tags");
    if (postDocumentRequest.ArchiveSerialNumber != null)
      content.Add(new StringContent(postDocumentRequest.ArchiveSerialNumber.Value.ToString()), "archive_serial_number");
    if (postDocumentRequest.CustomFields != null)
      content.Add(new StringContent(JsonSerializer.Serialize(postDocumentRequest.CustomFields, JsonConfig.Default)), "custom_fields");
    if (postDocumentRequest.FromWebui != null)
      content.Add(new StringContent(postDocumentRequest.FromWebui.Value.ToString().ToLowerInvariant()), "from_webui");
    return content;
  }
  public static MultipartFormDataContent ToMultipartContent(this Apigen.PaperlessNgx.Models.DocumentListRequest documentListRequest)
  {
    MultipartFormDataContent content = new();
    if (documentListRequest.Documents != null)
      content.Add(new StringContent(JsonSerializer.Serialize(documentListRequest.Documents, JsonConfig.Default)), "documents");
    return content;
  }
}
