//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// AISuggestions from OpenAPI schema.
/// Schema path: #/components/schemas/AISuggestions
/// </summary>
public partial class AISuggestions
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("correspondents")]
  public List<int>? Correspondents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("suggested_correspondents")]
  public List<string?>? SuggestedCorrespondents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public List<int>? Tags { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("suggested_tags")]
  public List<string?>? SuggestedTags { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_types")]
  public List<int>? DocumentTypes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("suggested_document_types")]
  public List<string?>? SuggestedDocumentTypes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storage_paths")]
  public List<int>? StoragePaths { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("suggested_storage_paths")]
  public List<string?>? SuggestedStoragePaths { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("dates")]
  public List<string?>? Dates { get; set; }
}
