//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// 1 - Only process attachments.
/// 2 - Process all files, including &apos;inline&apos; attachments.
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<AttachmentTypeEnum>))]
public enum AttachmentTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "1")]
    OnlyAttachments = 1,

    [EnumMember(Value = "2")]
    AllFiles = 2
}
