//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// BasicUserRequest from OpenAPI schema.
/// Schema path: #/components/schemas/BasicUserRequest
/// </summary>
public class BasicUserRequest
{
  /// <summary>
  /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(150)]
  [RegularExpression(@"^[\w.@+-]+$")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [MaxLength(150)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("first_name")]
  public string? FirstName { get; set; }

  [MaxLength(150)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("last_name")]
  public string? LastName { get; set; }
}
