//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// BulkDownload from OpenAPI schema.
/// Schema path: #/components/schemas/BulkDownload
/// </summary>
public partial class BulkDownload
{
  [System.Text.Json.Serialization.JsonPropertyName("content")]
  public ContentEnum? Content { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("compression")]
  public CompressionEnum? Compression { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("follow_formatting")]
  public bool? FollowFormatting { get; set; }
}
