//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// BulkEditRequest from OpenAPI schema.
/// Schema path: #/components/schemas/BulkEditRequest
/// </summary>
public partial class BulkEditRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("documents")]
  public List<int>? Documents { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("all")]
  public bool? All { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("filters")]
  public Dictionary<string, object?>? Filters { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("method")]
  public MethodEnum Method { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("parameters")]
  public Dictionary<string, object?>? Parameters { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("from_webui")]
  public bool? FromWebui { get; set; }
}
