//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// ChatStreamingRequest from OpenAPI schema.
/// Schema path: #/components/schemas/ChatStreamingRequest
/// </summary>
public partial class ChatStreamingRequest
{
  [Required]
  [MinLength(1)]
  [MaxLength(4000)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("q")]
  public string? Q { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("document_id")]
  public int? DocumentId { get; set; }
}
