//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Classifier from OpenAPI schema.
/// Schema path: #/components/schemas/Classifier
/// </summary>
public partial class Classifier
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("last_trained")]
  public DateTime LastTrained { get; set; }
}
