//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// LeaveColorUnchanged - LeaveColorUnchanged
/// RGB - RGB
/// UseDeviceIndependentColor - UseDeviceIndependentColor
/// Gray - Gray
/// CMYK - CMYK
/// </summary>
public enum ColorConversionStrategyEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "LeaveColorUnchanged")]
    _LeaveColorUnchanged,

    [EnumMember(Value = "RGB")]
    _RGB,

    [EnumMember(Value = "UseDeviceIndependentColor")]
    _UseDeviceIndependentColor,

    [EnumMember(Value = "Gray")]
    _Gray,

    [EnumMember(Value = "CMYK")]
    _CMYK
}
