//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// ConfigUpdateRequest from OpenAPI schema.
/// Schema path: #/components/schemas/ConfigUpdateRequest
/// </summary>
public class ConfigUpdateRequest
{
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("user_args")]
  public object? UserArgs { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_tag_mapping")]
  public object? BarcodeTagMapping { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("output_type")]
  public object? OutputType { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("pages")]
  public int? Pages { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public object? Mode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("skip_archive_file")]
  public object? SkipArchiveFile { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("image_dpi")]
  public int? ImageDpi { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("unpaper_clean")]
  public object? UnpaperClean { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deskew")]
  public bool? Deskew { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rotate_pages")]
  public bool? RotatePages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rotate_pages_threshold")]
  public double? RotatePagesThreshold { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_image_pixels")]
  public double? MaxImagePixels { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("color_conversion_strategy")]
  public object? ColorConversionStrategy { get; set; }

  [MaxLength(48)]
  [System.Text.Json.Serialization.JsonPropertyName("app_title")]
  public string? AppTitle { get; set; }

  [RegularExpression(@"(?:jpg|png|gif|svg)$")]
  [System.Text.Json.Serialization.JsonPropertyName("app_logo")]
  public byte[]? AppLogo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcodes_enabled")]
  public bool? BarcodesEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_tiff_support")]
  public bool? BarcodeEnableTiffSupport { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_string")]
  public string? BarcodeString { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_retain_split_pages")]
  public bool? BarcodeRetainSplitPages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_asn")]
  public bool? BarcodeEnableAsn { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_asn_prefix")]
  public string? BarcodeAsnPrefix { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_upscale")]
  public double? BarcodeUpscale { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_dpi")]
  public int? BarcodeDpi { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_max_pages")]
  public int? BarcodeMaxPages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_tag")]
  public bool? BarcodeEnableTag { get; set; }
}
