//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// CustomField from OpenAPI schema.
/// Schema path: #/components/schemas/CustomField
/// </summary>
public class CustomField
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// string - string
  /// url - url
  /// date - date
  /// boolean - boolean
  /// integer - integer
  /// float - float
  /// monetary - monetary
  /// documentlink - documentlink
  /// select - select
  /// longtext - longtext
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data_type")]
  public DataTypeEnum DataType { get; set; }

  /// <summary>
  /// Extra data for the custom field, such as select options
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("extra_data")]
  public object? ExtraData { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_count")]
  public int DocumentCount { get; set; }
}
