//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// CustomFieldInstanceRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CustomFieldInstanceRequest
/// </summary>
public partial class CustomFieldInstanceRequest
{
  /// <summary>
  /// Given the *incoming* primitive data, return the value for this field
  /// that should be validated and transformed to a native value.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public object? Value { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("field")]
  public int Field { get; set; }
}
