//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// string - string
/// url - url
/// date - date
/// boolean - boolean
/// integer - integer
/// float - float
/// monetary - monetary
/// documentlink - documentlink
/// select - select
/// </summary>
public enum DataTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "string")]
    _string,

    [EnumMember(Value = "url")]
    _url,

    [EnumMember(Value = "date")]
    _date,

    [EnumMember(Value = "boolean")]
    _boolean,

    [EnumMember(Value = "integer")]
    _integer,

    [EnumMember(Value = "float")]
    _float,

    [EnumMember(Value = "monetary")]
    _monetary,

    [EnumMember(Value = "documentlink")]
    _documentlink,

    [EnumMember(Value = "select")]
    _select
}
