//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Database from OpenAPI schema.
/// Schema path: #/components/schemas/Database
/// </summary>
public partial class DatabaseStatus
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("migration_status")]
  public MigrationStatus MigrationStatus { get; set; } = null!;
}
