//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// DocumentVersionInfo from OpenAPI schema.
/// Schema path: #/components/schemas/DocumentVersionInfo
/// </summary>
public partial class DocumentVersionInfo
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("added")]
  public DateTimeOffset Added { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("version_label")]
  public string? VersionLabel { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("checksum")]
  public string? Checksum { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("is_root")]
  public bool IsRoot { get; set; }
}
