//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// DocumentType from OpenAPI schema.
/// Schema path: #/components/schemas/DocumentType
/// </summary>
public class DocumentType
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }

  [Required]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("match")]
  public string? Match { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("matching_algorithm")]
  public MatchingAlgorithm? MatchingAlgorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_insensitive")]
  public bool? IsInsensitive { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_count")]
  public int DocumentCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public object? Permissions { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user_can_change")]
  public bool UserCanChange { get; set; }
}
