//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Document from OpenAPI schema.
/// Schema path: #/components/schemas/Document
/// 
/// Adds update nested feature
/// </summary>
public class Document
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("correspondent")]
  public int? Correspondent { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_type")]
  public int? DocumentType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storage_path")]
  public int? StoragePath { get; set; }

  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The raw, text-only data of the document. This field is primarily used for searching.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("content")]
  public string? Content { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public List<int>? Tags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public DateOnly? Created { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("created_date")]
  public DateOnly? CreatedDate { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("modified")]
  public DateTime Modified { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("added")]
  public DateTime Added { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deleted_at")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// The position of this document in your physical document archive.
  /// </summary>
  [Range(0, 4294967295)]
  [System.Text.Json.Serialization.JsonPropertyName("archive_serial_number")]
  public long? ArchiveSerialNumber { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_file_name")]
  public string? OriginalFileName { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("archived_file_name")]
  public string? ArchivedFileName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public object? Permissions { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user_can_change")]
  public bool UserCanChange { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("is_shared_by_requester")]
  public bool IsSharedByRequester { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public List<Notes>? Notes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("custom_fields")]
  public List<CustomFieldInstance>? CustomFields { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("page_count")]
  public int? PageCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mime_type")]
  public string? MimeType { get; set; }
}
