//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// archive - Archive
/// original - Original
/// </summary>
public enum FileVersionEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "archive")]
    Archive,

    [EnumMember(Value = "original")]
    Original
}
