//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// archive - Archive
/// bank - Bank
/// basket - Basket
/// bell - Bell
/// bookmark - Bookmark
/// boxes - Boxes
/// briefcase - Briefcase
/// building - Building
/// calculator - Calculator
/// calendar - Calendar
/// camera - Camera
/// card-checklist - Checklist
/// cash - Cash
/// chat-left-text - Chat
/// check-circle - Check
/// clipboard - Clipboard
/// clock-history - Clock
/// credit-card - Credit card
/// download - Download
/// envelope - Envelope
/// exclamation-triangle - Warning
/// file-earmark - File
/// file-earmark-check - Checked file
/// file-earmark-lock - Locked file
/// file-earmark-medical - Medical file
/// file-earmark-person - Person file
/// file-earmark-spreadsheet - Spreadsheet
/// file-text - Text file
/// files - Files
/// folder - Folder
/// funnel - Filter
/// gear - Gear
/// globe2 - Globe
/// hash - Hash
/// heart - Heart
/// house - House
/// inbox - Inbox
/// journals - Journals
/// list-task - Task list
/// newspaper - Newspaper
/// paperclip - Attachment
/// people - People
/// person - Person
/// printer - Printer
/// receipt - Receipt
/// safe - Safe
/// search - Search
/// send - Send
/// shop - Shop
/// stack - Stack
/// stars - Stars
/// tag - Tag
/// tags - Tags
/// telephone - Telephone
/// truck - Truck
/// upc-scan - Barcode
/// wallet2 - Wallet
/// </summary>
public enum IconEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "archive")]
    Archive,

    [EnumMember(Value = "bank")]
    Bank,

    [EnumMember(Value = "basket")]
    Basket,

    [EnumMember(Value = "bell")]
    Bell,

    [EnumMember(Value = "bookmark")]
    Bookmark,

    [EnumMember(Value = "boxes")]
    Boxes,

    [EnumMember(Value = "briefcase")]
    Briefcase,

    [EnumMember(Value = "building")]
    Building,

    [EnumMember(Value = "calculator")]
    Calculator,

    [EnumMember(Value = "calendar")]
    Calendar,

    [EnumMember(Value = "camera")]
    Camera,

    [EnumMember(Value = "card-checklist")]
    CardChecklist,

    [EnumMember(Value = "cash")]
    Cash,

    [EnumMember(Value = "chat-left-text")]
    ChatLeftText,

    [EnumMember(Value = "check-circle")]
    CheckCircle,

    [EnumMember(Value = "clipboard")]
    Clipboard,

    [EnumMember(Value = "clock-history")]
    ClockHistory,

    [EnumMember(Value = "credit-card")]
    CreditCard,

    [EnumMember(Value = "download")]
    Download,

    [EnumMember(Value = "envelope")]
    Envelope,

    [EnumMember(Value = "exclamation-triangle")]
    ExclamationTriangle,

    [EnumMember(Value = "file-earmark")]
    FileEarmark,

    [EnumMember(Value = "file-earmark-check")]
    FileEarmarkCheck,

    [EnumMember(Value = "file-earmark-lock")]
    FileEarmarkLock,

    [EnumMember(Value = "file-earmark-medical")]
    FileEarmarkMedical,

    [EnumMember(Value = "file-earmark-person")]
    FileEarmarkPerson,

    [EnumMember(Value = "file-earmark-spreadsheet")]
    FileEarmarkSpreadsheet,

    [EnumMember(Value = "file-text")]
    FileText,

    [EnumMember(Value = "files")]
    Files,

    [EnumMember(Value = "folder")]
    Folder,

    [EnumMember(Value = "funnel")]
    Funnel,

    [EnumMember(Value = "gear")]
    Gear,

    [EnumMember(Value = "globe2")]
    Globe2,

    [EnumMember(Value = "hash")]
    Hash,

    [EnumMember(Value = "heart")]
    Heart,

    [EnumMember(Value = "house")]
    House,

    [EnumMember(Value = "inbox")]
    Inbox,

    [EnumMember(Value = "journals")]
    Journals,

    [EnumMember(Value = "list-task")]
    ListTask,

    [EnumMember(Value = "newspaper")]
    Newspaper,

    [EnumMember(Value = "paperclip")]
    Paperclip,

    [EnumMember(Value = "people")]
    People,

    [EnumMember(Value = "person")]
    Person,

    [EnumMember(Value = "printer")]
    Printer,

    [EnumMember(Value = "receipt")]
    Receipt,

    [EnumMember(Value = "safe")]
    Safe,

    [EnumMember(Value = "search")]
    Search,

    [EnumMember(Value = "send")]
    Send,

    [EnumMember(Value = "shop")]
    Shop,

    [EnumMember(Value = "stack")]
    Stack,

    [EnumMember(Value = "stars")]
    Stars,

    [EnumMember(Value = "tag")]
    Tag,

    [EnumMember(Value = "tags")]
    Tags,

    [EnumMember(Value = "telephone")]
    Telephone,

    [EnumMember(Value = "truck")]
    Truck,

    [EnumMember(Value = "upc-scan")]
    UpcScan,

    [EnumMember(Value = "wallet2")]
    Wallet2
}
