//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// LogEntry from OpenAPI schema.
/// Schema path: #/components/schemas/LogEntry
/// </summary>
public class LogEntry
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
  public DateTime Timestamp { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("changes")]
  public Dictionary<string, object?>? Changes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("actor")]
  public Actor Actor { get; set; } = null!;
}
