//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// MailAccount from OpenAPI schema.
/// Schema path: #/components/schemas/MailAccount
/// </summary>
public partial class MailAccount
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [Required]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("imap_server")]
  public string? ImapServer { get; set; }

  /// <summary>
  /// This is usually 143 for unencrypted and STARTTLS connections, and 993 for SSL connections.
  /// </summary>
  [Range(0, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("imap_port")]
  public int? ImapPort { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("imap_security")]
  public ImapSecurityEnum? ImapSecurity { get; set; }

  [Required]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The character set to use when communicating with the mail server, such as &apos;UTF-8&apos; or &apos;US-ASCII&apos;.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("character_set")]
  public string? CharacterSet { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_token")]
  public bool? IsToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user_can_change")]
  public bool UserCanChange { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("account_type")]
  public AccountTypeEnum? AccountType { get; set; }

  /// <summary>
  /// The expiration date of the refresh token.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiration")]
  public DateTimeOffset? Expiration { get; set; }
}
