//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// 1 - Delete
/// 2 - Move to specified folder
/// 3 - Mark as read, don&apos;t process read mails
/// 4 - Flag the mail, don&apos;t process flagged mails
/// 5 - Tag the mail with specified tag, don&apos;t process tagged mails
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<MailRuleActionEnum>))]
public enum MailRuleActionEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "1")]
    _1 = 1,

    [EnumMember(Value = "2")]
    _2 = 2,

    [EnumMember(Value = "3")]
    _3 = 3,

    [EnumMember(Value = "4")]
    _4 = 4,

    [EnumMember(Value = "5")]
    _5 = 5
}
