//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Metadata from OpenAPI schema.
/// Schema path: #/components/schemas/Metadata
/// </summary>
public partial class Metadata
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_checksum")]
  public string? OriginalChecksum { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_size")]
  public int OriginalSize { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_mime_type")]
  public string? OriginalMimeType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("media_filename")]
  public string? MediaFilename { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("has_archive_version")]
  public bool HasArchiveVersion { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_metadata")]
  public List<OriginalMetadataEntry>? OriginalMetadata { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archive_checksum")]
  public string? ArchiveChecksum { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archive_media_filename")]
  public string? ArchiveMediaFilename { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("original_filename")]
  public string? OriginalFilename { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archive_size")]
  public int? ArchiveSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archive_metadata")]
  public List<ArchiveMetadataEntry>? ArchiveMetadata { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lang")]
  public string? Lang { get; set; }
}
