//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// set_correspondent - set_correspondent
/// set_document_type - set_document_type
/// set_storage_path - set_storage_path
/// add_tag - add_tag
/// remove_tag - remove_tag
/// modify_tags - modify_tags
/// modify_custom_fields - modify_custom_fields
/// set_permissions - set_permissions
/// delete - delete
/// reprocess - reprocess
/// rotate - rotate
/// merge - merge
/// edit_pdf - edit_pdf
/// remove_password - remove_password
/// split - split
/// delete_pages - delete_pages
/// </summary>
public enum MethodEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "set_correspondent")]
    SetCorrespondent,

    [EnumMember(Value = "set_document_type")]
    SetDocumentType,

    [EnumMember(Value = "set_storage_path")]
    SetStoragePath,

    [EnumMember(Value = "add_tag")]
    AddTag,

    [EnumMember(Value = "remove_tag")]
    RemoveTag,

    [EnumMember(Value = "modify_tags")]
    ModifyTags,

    [EnumMember(Value = "modify_custom_fields")]
    ModifyCustomFields,

    [EnumMember(Value = "set_permissions")]
    SetPermissions,

    [EnumMember(Value = "delete")]
    Delete,

    [EnumMember(Value = "reprocess")]
    Reprocess,

    [EnumMember(Value = "rotate")]
    Rotate,

    [EnumMember(Value = "merge")]
    Merge,

    [EnumMember(Value = "edit_pdf")]
    EditPdf,

    [EnumMember(Value = "remove_password")]
    RemovePassword,

    [EnumMember(Value = "split")]
    Split,

    [EnumMember(Value = "delete_pages")]
    DeletePages
}
