//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Notes from OpenAPI schema.
/// Schema path: #/components/schemas/Notes
/// </summary>
public partial class Note
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  /// <summary>
  /// Note for the document
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("note")]
  public string? NoteValue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public DateTimeOffset? Created { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public BasicUser User { get; set; } = null!;
}
