//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// tags - tags
/// correspondents - correspondents
/// document_types - document_types
/// storage_paths - storage_paths
/// </summary>
public enum ObjectTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "tags")]
    Tags,

    [EnumMember(Value = "correspondents")]
    Correspondents,

    [EnumMember(Value = "document_types")]
    DocumentTypes,

    [EnumMember(Value = "storage_paths")]
    StoragePaths
}
