//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// OriginalMetadataEntry from OpenAPI schema.
/// Schema path: #/components/schemas/OriginalMetadataEntry
/// </summary>
public partial class OriginalMetadataEntry
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("namespace")]
  public string? Namespace { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("prefix")]
  public string? Prefix { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
