//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// pdf - pdf
/// pdfa - pdfa
/// pdfa-1 - pdfa-1
/// pdfa-2 - pdfa-2
/// pdfa-3 - pdfa-3
/// </summary>
public enum OutputTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "pdf")]
    _pdf,

    [EnumMember(Value = "pdfa")]
    _pdfa,

    [EnumMember(Value = "pdfa-1")]
    _pdfa1,

    [EnumMember(Value = "pdfa-2")]
    _pdfa2,

    [EnumMember(Value = "pdfa-3")]
    _pdfa3
}
