//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PaginatedWorkflowList from OpenAPI schema.
/// Schema path: #/components/schemas/PaginatedWorkflowList
/// </summary>
public class PaginatedWorkflowList
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public int Count { get; set; }

  [Url]
  [System.Text.Json.Serialization.JsonPropertyName("next")]
  public string? Next { get; set; }

  [Url]
  [System.Text.Json.Serialization.JsonPropertyName("previous")]
  public string? Previous { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("results")]
  public List<Workflow>? Results { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("all")]
  public List<int>? All { get; set; }
}
