//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// TaskSerializerV10 from OpenAPI schema.
/// Schema path: #/components/schemas/TaskSerializerV10
/// 
/// Task serializer for API v10+ using new field names.
/// </summary>
public partial class PaperlessTask
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  /// <summary>
  /// Celery task ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public string? TaskId { get; set; }

  /// <summary>
  /// The kind of work being performed
  /// 
  /// consume_file - Consume File
  /// train_classifier - Train Classifier
  /// sanity_check - Sanity Check
  /// index_optimize - Index Optimize
  /// mail_fetch - Mail Fetch
  /// llm_index - LLM Index
  /// empty_trash - Empty Trash
  /// check_workflows - Check Workflows
  /// bulk_update - Bulk Update
  /// reprocess_document - Reprocess Document
  /// build_share_link - Build Share Link
  /// bulk_delete - Bulk Delete
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("task_type")]
  public TaskTypeEnum TaskType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("task_type_display")]
  public string? TaskTypeDisplay { get; set; }

  /// <summary>
  /// What initiated this task
  /// 
  /// scheduled - Scheduled
  /// web_ui - Web UI
  /// api_upload - API Upload
  /// folder_consume - Folder Consume
  /// email_consume - Email Consume
  /// system - System
  /// manual - Manual
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trigger_source")]
  public TriggerSourceEnum TriggerSource { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trigger_source_display")]
  public string? TriggerSourceDisplay { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public PaperlessTaskStatusEnum Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status_display")]
  public string? StatusDisplay { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date_created")]
  public DateTimeOffset DateCreated { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date_started")]
  public DateTimeOffset? DateStarted { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("date_done")]
  public DateTimeOffset? DateDone { get; set; }

  /// <summary>
  /// Elapsed time from start to completion
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duration_seconds")]
  public double? DurationSeconds { get; set; }

  /// <summary>
  /// Time from task creation to worker pickup
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("wait_time_seconds")]
  public double? WaitTimeSeconds { get; set; }

  /// <summary>
  /// Structured input parameters for the task
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("input_data")]
  public object? InputData { get; set; }

  /// <summary>
  /// Structured result data from task execution
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("result_data")]
  public object? ResultData { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("related_document_ids")]
  public List<int>? RelatedDocumentIds { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("acknowledged")]
  public bool Acknowledged { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }
}
