//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PaperlessAuthToken from OpenAPI schema.
/// Schema path: #/components/schemas/PaperlessAuthToken
/// </summary>
public partial class PaperlessAuthToken
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }
}
