//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PatchedApplicationConfigurationRequest from OpenAPI schema.
/// Schema path: #/components/schemas/PatchedApplicationConfigurationRequest
/// </summary>
public partial class PatchedApplicationConfigurationRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("user_args")]
  public object? UserArgs { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_tag_mapping")]
  public object? BarcodeTagMapping { get; set; }

  [MinLength(1)]
  [MaxLength(1024)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_api_key")]
  public string? LlmApiKey { get; set; }

  [MinLength(1)]
  [MaxLength(1024)]
  [System.Text.Json.Serialization.JsonPropertyName("remote_ocr_api_key")]
  public string? RemoteOcrApiKey { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("output_type")]
  public OutputTypeEnum? OutputType { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("pages")]
  public long? Pages { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public ModeEnum? Mode { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("archive_file_generation")]
  public ArchiveFileGenerationEnum? ArchiveFileGeneration { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("image_dpi")]
  public long? ImageDpi { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("unpaper_clean")]
  public UnpaperCleanEnum? UnpaperClean { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deskew")]
  public bool? Deskew { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rotate_pages")]
  public bool? RotatePages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rotate_pages_threshold")]
  public double? RotatePagesThreshold { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_image_pixels")]
  public double? MaxImagePixels { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("color_conversion_strategy")]
  public ColorConversionStrategyEnum? ColorConversionStrategy { get; set; }

  [MaxLength(48)]
  [System.Text.Json.Serialization.JsonPropertyName("app_title")]
  public string? AppTitle { get; set; }

  [RegularExpression(@"(?:jpg|png|gif|svg)$")]
  [System.Text.Json.Serialization.JsonPropertyName("app_logo")]
  public byte[]? AppLogo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcodes_enabled")]
  public bool? BarcodesEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_tiff_support")]
  public bool? BarcodeEnableTiffSupport { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_string")]
  public string? BarcodeString { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_retain_split_pages")]
  public bool? BarcodeRetainSplitPages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_asn")]
  public bool? BarcodeEnableAsn { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_asn_prefix")]
  public string? BarcodeAsnPrefix { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_upscale")]
  public double? BarcodeUpscale { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_dpi")]
  public long? BarcodeDpi { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("barcode_max_pages")]
  public long? BarcodeMaxPages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_enable_tag")]
  public bool? BarcodeEnableTag { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("barcode_tag_split")]
  public bool? BarcodeTagSplit { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("remote_ocr_engine")]
  public RemoteOcrEngineEnum? RemoteOcrEngine { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("remote_ocr_endpoint")]
  public string? RemoteOcrEndpoint { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("remote_ocr_mode")]
  public RemoteOcrModeEnum? RemoteOcrMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ai_enabled")]
  public bool? AiEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_embedding_backend")]
  public LlmEmbeddingBackendEnum? LlmEmbeddingBackend { get; set; }

  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_embedding_model")]
  public string? LlmEmbeddingModel { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_embedding_endpoint")]
  public string? LlmEmbeddingEndpoint { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_embedding_chunk_size")]
  public long? LlmEmbeddingChunkSize { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_context_size")]
  public long? LlmContextSize { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_backend")]
  public LlmBackendEnum? LlmBackend { get; set; }

  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_model")]
  public string? LlmModel { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_endpoint")]
  public string? LlmEndpoint { get; set; }

  [MaxLength(32)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_output_language")]
  public string? LlmOutputLanguage { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("llm_request_timeout")]
  public long? LlmRequestTimeout { get; set; }
}
