//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PatchedMailRuleRequest from OpenAPI schema.
/// Schema path: #/components/schemas/PatchedMailRuleRequest
/// </summary>
public partial class PatchedMailRuleRequest
{
  [MinLength(1)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("account")]
  public int? Account { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  /// <summary>
  /// Subfolders must be separated by a delimiter, often a dot (&apos;.&apos;) or slash (&apos;/&apos;), but it varies by mail server.
  /// </summary>
  [MinLength(1)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("folder")]
  public string? Folder { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_from")]
  public string? FilterFrom { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_to")]
  public string? FilterTo { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_subject")]
  public string? FilterSubject { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_body")]
  public string? FilterBody { get; set; }

  /// <summary>
  /// Only consume documents which entirely match this filename if specified. Wildcards such as *.pdf or *invoice* are allowed. Case insensitive.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_attachment_filename_include")]
  public string? FilterAttachmentFilenameInclude { get; set; }

  /// <summary>
  /// Do not consume documents which entirely match this filename if specified. Wildcards such as *.pdf or *invoice* are allowed. Case insensitive.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_attachment_filename_exclude")]
  public string? FilterAttachmentFilenameExclude { get; set; }

  /// <summary>
  /// Specified in days.
  /// </summary>
  [Range(0, 2147483647)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("maximum_age")]
  public int? MaximumAge { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public MailRuleActionEnum? Action { get; set; }

  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("action_parameter")]
  public string? ActionParameter { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assign_title_from")]
  public AssignTitleFromEnum? AssignTitleFrom { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assign_tags")]
  public List<int?>? AssignTags { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assign_correspondent_from")]
  public AssignCorrespondentFromEnum? AssignCorrespondentFrom { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_correspondent")]
  public int? AssignCorrespondent { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_document_type")]
  public int? AssignDocumentType { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assign_owner_from_rule")]
  public bool? AssignOwnerFromRule { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("order")]
  public int? Order { get; set; }

  /// <summary>
  /// Inline attachments include embedded images, so it&apos;s best to combine this option with a filename filter.
  /// 
  /// 1 - Only process attachments.
  /// 2 - Process all files, including &apos;inline&apos; attachments.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("attachment_type")]
  public AttachmentTypeEnum? AttachmentType { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("consumption_scope")]
  public ConsumptionScopeEnum? ConsumptionScope { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("pdf_layout")]
  public PdfLayoutEnum? PdfLayout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("set_permissions")]
  public object? SetPermissions { get; set; }
}
