//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PatchedSavedViewRequest from OpenAPI schema.
/// Schema path: #/components/schemas/PatchedSavedViewRequest
/// </summary>
public class PatchedSavedViewRequest
{
  [MinLength(1)]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("show_on_dashboard")]
  public bool? ShowOnDashboard { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("show_in_sidebar")]
  public bool? ShowInSidebar { get; set; }

  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("sort_field")]
  public string? SortField { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("sort_reverse")]
  public bool? SortReverse { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_rules")]
  public List<SavedViewFilterRuleRequest>? FilterRules { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("page_size")]
  public int? PageSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("display_mode")]
  public DisplayModeEnum? DisplayMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("display_fields")]
  public object? DisplayFields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }
}
