//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// 0 - System default
/// 1 - Text, then HTML
/// 2 - HTML, then text
/// 3 - HTML only
/// 4 - Text only
/// </summary>
public enum PdfLayoutEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "0")]
    _0 = 0,

    [EnumMember(Value = "1")]
    _1 = 1,

    [EnumMember(Value = "2")]
    _2 = 2,

    [EnumMember(Value = "3")]
    _3 = 3,

    [EnumMember(Value = "4")]
    _4 = 4
}
