//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// PostDocumentRequest from OpenAPI schema.
/// Schema path: #/components/schemas/PostDocumentRequest
/// </summary>
public partial class PostDocumentRequest
{
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public DateTimeOffset? Created { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document")]
  public required byte[] Document { get; set; }

  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("correspondent")]
  public int? Correspondent { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("document_type")]
  public int? DocumentType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("storage_path")]
  public int? StoragePath { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public List<int>? Tags { get; set; }

  [Range(0, 4294967295)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("archive_serial_number")]
  public long? ArchiveSerialNumber { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("custom_fields")]
  public List<int>? CustomFields { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("from_webui")]
  public bool? FromWebui { get; set; }
}
