//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// ProcessedMail from OpenAPI schema.
/// Schema path: #/components/schemas/ProcessedMail
/// </summary>
public partial class ProcessedMail
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("rule")]
  public int Rule { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("folder")]
  public string? Folder { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("uid")]
  public string? Uid { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("subject")]
  public string? Subject { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("received")]
  public DateTimeOffset Received { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("processed")]
  public DateTimeOffset Processed { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }
}
