//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Profile from OpenAPI schema.
/// Schema path: #/components/schemas/Profile
/// </summary>
public partial class Profile
{
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  [MaxLength(150)]
  [System.Text.Json.Serialization.JsonPropertyName("first_name")]
  public string? FirstName { get; set; }

  [MaxLength(150)]
  [System.Text.Json.Serialization.JsonPropertyName("last_name")]
  public string? LastName { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("auth_token")]
  public string? AuthToken { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("social_accounts")]
  public List<SocialAccount>? SocialAccounts { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("has_usable_password")]
  public bool HasUsablePassword { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("is_mfa_enabled")]
  public bool IsMfaEnabled { get; set; }
}
