//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// 0 - title contains
/// 1 - content contains
/// 2 - ASN is
/// 3 - correspondent is
/// 4 - document type is
/// 5 - is in inbox
/// 6 - has tag
/// 7 - has any tag
/// 8 - created before
/// 9 - created after
/// 10 - created year is
/// 11 - created month is
/// 12 - created day is
/// 13 - added before
/// 14 - added after
/// 15 - modified before
/// 16 - modified after
/// 17 - does not have tag
/// 18 - does not have ASN
/// 19 - title or content contains
/// 20 - fulltext query
/// 21 - more like this
/// 22 - has tags in
/// 23 - ASN greater than
/// 24 - ASN less than
/// 25 - storage path is
/// 26 - has correspondent in
/// 27 - does not have correspondent in
/// 28 - has document type in
/// 29 - does not have document type in
/// 30 - has storage path in
/// 31 - does not have storage path in
/// 32 - owner is
/// 33 - has owner in
/// 34 - does not have owner
/// 35 - does not have owner in
/// 36 - has custom field value
/// 37 - is shared by me
/// 38 - has custom fields
/// 39 - has custom field in
/// 40 - does not have custom field in
/// 41 - does not have custom field
/// 42 - custom fields query
/// 43 - created to
/// 44 - created from
/// 45 - added to
/// 46 - added from
/// 47 - mime type is
/// </summary>
public enum RuleTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "0")]
    TitleContains = 0,

    [EnumMember(Value = "1")]
    ContentContains = 1,

    [EnumMember(Value = "2")]
    AsnIs = 2,

    [EnumMember(Value = "3")]
    CorrespondentIs = 3,

    [EnumMember(Value = "4")]
    DocumentTypeIs = 4,

    [EnumMember(Value = "5")]
    IsInInbox = 5,

    [EnumMember(Value = "6")]
    HasTag = 6,

    [EnumMember(Value = "7")]
    HasAnyTag = 7,

    [EnumMember(Value = "8")]
    CreatedBefore = 8,

    [EnumMember(Value = "9")]
    CreatedAfter = 9,

    [EnumMember(Value = "10")]
    CreatedYearIs = 10,

    [EnumMember(Value = "11")]
    CreatedMonthIs = 11,

    [EnumMember(Value = "12")]
    CreatedDayIs = 12,

    [EnumMember(Value = "13")]
    AddedBefore = 13,

    [EnumMember(Value = "14")]
    AddedAfter = 14,

    [EnumMember(Value = "15")]
    ModifiedBefore = 15,

    [EnumMember(Value = "16")]
    ModifiedAfter = 16,

    [EnumMember(Value = "17")]
    DoesNotHaveTag = 17,

    [EnumMember(Value = "18")]
    DoesNotHaveAsn = 18,

    [EnumMember(Value = "19")]
    TitleOrContentContains = 19,

    [EnumMember(Value = "20")]
    FulltextQuery = 20,

    [EnumMember(Value = "21")]
    MoreLikeThis = 21,

    [EnumMember(Value = "22")]
    HasTagsIn = 22,

    [EnumMember(Value = "23")]
    AsnGreaterThan = 23,

    [EnumMember(Value = "24")]
    AsnLessThan = 24,

    [EnumMember(Value = "25")]
    StoragePathIs = 25,

    [EnumMember(Value = "26")]
    HasCorrespondentIn = 26,

    [EnumMember(Value = "27")]
    DoesNotHaveCorrespondentIn = 27,

    [EnumMember(Value = "28")]
    HasDocumentTypeIn = 28,

    [EnumMember(Value = "29")]
    DoesNotHaveDocumentTypeIn = 29,

    [EnumMember(Value = "30")]
    HasStoragePathIn = 30,

    [EnumMember(Value = "31")]
    DoesNotHaveStoragePathIn = 31,

    [EnumMember(Value = "32")]
    OwnerIs = 32,

    [EnumMember(Value = "33")]
    HasOwnerIn = 33,

    [EnumMember(Value = "34")]
    DoesNotHaveOwner = 34,

    [EnumMember(Value = "35")]
    DoesNotHaveOwnerIn = 35,

    [EnumMember(Value = "36")]
    HasCustomFieldValue = 36,

    [EnumMember(Value = "37")]
    IsSharedByMe = 37,

    [EnumMember(Value = "38")]
    HasCustomFields = 38,

    [EnumMember(Value = "39")]
    HasCustomFieldIn = 39,

    [EnumMember(Value = "40")]
    DoesNotHaveCustomFieldIn = 40,

    [EnumMember(Value = "41")]
    DoesNotHaveCustomField = 41,

    [EnumMember(Value = "42")]
    CustomFieldsQuery = 42,

    [EnumMember(Value = "43")]
    CreatedTo = 43,

    [EnumMember(Value = "44")]
    CreatedFrom = 44,

    [EnumMember(Value = "45")]
    AddedTo = 45,

    [EnumMember(Value = "46")]
    AddedFrom = 46,

    [EnumMember(Value = "47")]
    MimeTypeIs = 47
}
