//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// 0 - title contains
/// 1 - content contains
/// 2 - ASN is
/// 3 - correspondent is
/// 4 - document type is
/// 5 - is in inbox
/// 6 - has tag
/// 7 - has any tag
/// 8 - created before
/// 9 - created after
/// 10 - created year is
/// 11 - created month is
/// 12 - created day is
/// 13 - added before
/// 14 - added after
/// 15 - modified before
/// 16 - modified after
/// 17 - does not have tag
/// 18 - does not have ASN
/// 19 - title or content contains
/// 20 - fulltext query
/// 21 - more like this
/// 22 - has tags in
/// 23 - ASN greater than
/// 24 - ASN less than
/// 25 - storage path is
/// 26 - has correspondent in
/// 27 - does not have correspondent in
/// 28 - has document type in
/// 29 - does not have document type in
/// 30 - has storage path in
/// 31 - does not have storage path in
/// 32 - owner is
/// 33 - has owner in
/// 34 - does not have owner
/// 35 - does not have owner in
/// 36 - has custom field value
/// 37 - is shared by me
/// 38 - has custom fields
/// 39 - has custom field in
/// 40 - does not have custom field in
/// 41 - does not have custom field
/// 42 - custom fields query
/// 43 - created to
/// 44 - created from
/// 45 - added to
/// 46 - added from
/// 47 - mime type is
/// </summary>
public enum RuleTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "0")]
    _0 = 0,

    [EnumMember(Value = "1")]
    _1 = 1,

    [EnumMember(Value = "2")]
    _2 = 2,

    [EnumMember(Value = "3")]
    _3 = 3,

    [EnumMember(Value = "4")]
    _4 = 4,

    [EnumMember(Value = "5")]
    _5 = 5,

    [EnumMember(Value = "6")]
    _6 = 6,

    [EnumMember(Value = "7")]
    _7 = 7,

    [EnumMember(Value = "8")]
    _8 = 8,

    [EnumMember(Value = "9")]
    _9 = 9,

    [EnumMember(Value = "10")]
    _10 = 10,

    [EnumMember(Value = "11")]
    _11 = 11,

    [EnumMember(Value = "12")]
    _12 = 12,

    [EnumMember(Value = "13")]
    _13 = 13,

    [EnumMember(Value = "14")]
    _14 = 14,

    [EnumMember(Value = "15")]
    _15 = 15,

    [EnumMember(Value = "16")]
    _16 = 16,

    [EnumMember(Value = "17")]
    _17 = 17,

    [EnumMember(Value = "18")]
    _18 = 18,

    [EnumMember(Value = "19")]
    _19 = 19,

    [EnumMember(Value = "20")]
    _20 = 20,

    [EnumMember(Value = "21")]
    _21 = 21,

    [EnumMember(Value = "22")]
    _22 = 22,

    [EnumMember(Value = "23")]
    _23 = 23,

    [EnumMember(Value = "24")]
    _24 = 24,

    [EnumMember(Value = "25")]
    _25 = 25,

    [EnumMember(Value = "26")]
    _26 = 26,

    [EnumMember(Value = "27")]
    _27 = 27,

    [EnumMember(Value = "28")]
    _28 = 28,

    [EnumMember(Value = "29")]
    _29 = 29,

    [EnumMember(Value = "30")]
    _30 = 30,

    [EnumMember(Value = "31")]
    _31 = 31,

    [EnumMember(Value = "32")]
    _32 = 32,

    [EnumMember(Value = "33")]
    _33 = 33,

    [EnumMember(Value = "34")]
    _34 = 34,

    [EnumMember(Value = "35")]
    _35 = 35,

    [EnumMember(Value = "36")]
    _36 = 36,

    [EnumMember(Value = "37")]
    _37 = 37,

    [EnumMember(Value = "38")]
    _38 = 38,

    [EnumMember(Value = "39")]
    _39 = 39,

    [EnumMember(Value = "40")]
    _40 = 40,

    [EnumMember(Value = "41")]
    _41 = 41,

    [EnumMember(Value = "42")]
    _42 = 42,

    [EnumMember(Value = "43")]
    _43 = 43,

    [EnumMember(Value = "44")]
    _44 = 44,

    [EnumMember(Value = "45")]
    _45 = 45,

    [EnumMember(Value = "46")]
    _46 = 46,

    [EnumMember(Value = "47")]
    _47 = 47
}
