//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// SavedView from OpenAPI schema.
/// Schema path: #/components/schemas/SavedView
/// </summary>
public partial class SavedView
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// archive - Archive
  /// bank - Bank
  /// basket - Basket
  /// bell - Bell
  /// bookmark - Bookmark
  /// boxes - Boxes
  /// briefcase - Briefcase
  /// building - Building
  /// calculator - Calculator
  /// calendar - Calendar
  /// camera - Camera
  /// card-checklist - Checklist
  /// cash - Cash
  /// chat-left-text - Chat
  /// check-circle - Check
  /// clipboard - Clipboard
  /// clock-history - Clock
  /// credit-card - Credit card
  /// download - Download
  /// envelope - Envelope
  /// exclamation-triangle - Warning
  /// file-earmark - File
  /// file-earmark-check - Checked file
  /// file-earmark-lock - Locked file
  /// file-earmark-medical - Medical file
  /// file-earmark-person - Person file
  /// file-earmark-spreadsheet - Spreadsheet
  /// file-text - Text file
  /// files - Files
  /// folder - Folder
  /// funnel - Filter
  /// gear - Gear
  /// globe2 - Globe
  /// hash - Hash
  /// heart - Heart
  /// house - House
  /// inbox - Inbox
  /// journals - Journals
  /// list-task - Task list
  /// newspaper - Newspaper
  /// paperclip - Attachment
  /// people - People
  /// person - Person
  /// printer - Printer
  /// receipt - Receipt
  /// safe - Safe
  /// search - Search
  /// send - Send
  /// shop - Shop
  /// stack - Stack
  /// stars - Stars
  /// tag - Tag
  /// tags - Tags
  /// telephone - Telephone
  /// truck - Truck
  /// upc-scan - Barcode
  /// wallet2 - Wallet
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("icon")]
  public IconEnum? Icon { get; set; }

  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("sort_field")]
  public string? SortField { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sort_reverse")]
  public bool? SortReverse { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("filter_rules")]
  public List<SavedViewFilterRule>? FilterRules { get; set; }

  [Range(1, 9223372036854775807)]
  [System.Text.Json.Serialization.JsonPropertyName("page_size")]
  public long? PageSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("display_mode")]
  public DisplayModeEnum? DisplayMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("display_fields")]
  public object? DisplayFields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public PermissionsSet Permissions { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user_can_change")]
  public bool UserCanChange { get; set; }
}
