//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// SavedViewFilterRuleRequest from OpenAPI schema.
/// Schema path: #/components/schemas/SavedViewFilterRuleRequest
/// </summary>
public class SavedViewFilterRuleRequest
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("rule_type")]
  public RuleTypeEnum RuleType { get; set; }

  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
