//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// SearchResult from OpenAPI schema.
/// Schema path: #/components/schemas/SearchResult
/// </summary>
public class SearchResult
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("documents")]
  public List<Document>? Documents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("saved_views")]
  public List<SavedView>? SavedViews { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public List<Tag>? Tags { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("correspondents")]
  public List<Correspondent>? Correspondents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_types")]
  public List<DocumentType>? DocumentTypes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storage_paths")]
  public List<StoragePath>? StoragePaths { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("users")]
  public List<User>? Users { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<Group>? Groups { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mail_rules")]
  public List<MailRule>? MailRules { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mail_accounts")]
  public List<MailAccount>? MailAccounts { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("workflows")]
  public List<Workflow>? Workflows { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("custom_fields")]
  public List<CustomField>? CustomFields { get; set; }
}
