//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// SelectionData from OpenAPI schema.
/// Schema path: #/components/schemas/SelectionData
/// </summary>
public partial class SelectionData
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("selected_correspondents")]
  public List<CorrespondentCounts>? SelectedCorrespondents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("selected_tags")]
  public List<TagCounts>? SelectedTags { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("selected_document_types")]
  public List<DocumentTypeCounts>? SelectedDocumentTypes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("selected_storage_paths")]
  public List<StoragePathCounts>? SelectedStoragePaths { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("selected_custom_fields")]
  public List<CustomFieldCounts>? SelectedCustomFields { get; set; }
}
