//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// ShareLinkBundle from OpenAPI schema.
/// Schema path: #/components/schemas/ShareLinkBundle
/// </summary>
public partial class ShareLinkBundle
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public DateTimeOffset Created { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("expiration")]
  public DateTimeOffset? Expiration { get; set; }

  [Required]
  [RegularExpression(@"^[-a-zA-Z0-9_]+$")]
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }

  /// <summary>
  /// archive - Archive
  /// original - Original
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("file_version")]
  public FileVersionEnum? FileVersion { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public ShareLinkBundleStatusEnum Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("size_bytes")]
  public int? SizeBytes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("last_error")]
  public object? LastError { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("built_at")]
  public DateTimeOffset? BuiltAt { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("documents")]
  public List<int>? Documents { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_count")]
  public int DocumentCount { get; set; }
}
