//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// FAILURE - FAILURE
/// PENDING - PENDING
/// RECEIVED - RECEIVED
/// RETRY - RETRY
/// REVOKED - REVOKED
/// STARTED - STARTED
/// SUCCESS - SUCCESS
/// </summary>
public enum StatusEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "FAILURE")]
    _FAILURE,

    [EnumMember(Value = "PENDING")]
    _PENDING,

    [EnumMember(Value = "RECEIVED")]
    _RECEIVED,

    [EnumMember(Value = "RETRY")]
    _RETRY,

    [EnumMember(Value = "REVOKED")]
    _REVOKED,

    [EnumMember(Value = "STARTED")]
    _STARTED,

    [EnumMember(Value = "SUCCESS")]
    _SUCCESS
}
