//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// StoragePathTestRequest from OpenAPI schema.
/// Schema path: #/components/schemas/StoragePathTestRequest
/// </summary>
public partial class StoragePathTestRequest
{
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("path")]
  public string? Path { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document")]
  public int Document { get; set; }
}
