//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Storage from OpenAPI schema.
/// Schema path: #/components/schemas/Storage
/// </summary>
public partial class Storage
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("available")]
  public int Available { get; set; }
}
