//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// SystemStatus from OpenAPI schema.
/// Schema path: #/components/schemas/SystemStatus
/// </summary>
public partial class SystemStatus
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pngx_version")]
  public string? PngxVersion { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("server_os")]
  public string? ServerOs { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("install_type")]
  public string? InstallType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storage")]
  public StorageStatus Storage { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("database")]
  public DatabaseStatus Database { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tasks")]
  public TaskQueueStatus Tasks { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("index")]
  public SearchIndexStatus Index { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("classifier")]
  public Classifier Classifier { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sanity_check")]
  public SanityCheck SanityCheck { get; set; } = null!;
}
