//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Tag from OpenAPI schema.
/// Schema path: #/components/schemas/Tag
/// </summary>
public partial class Tag
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }

  [Required]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MaxLength(7)]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("text_color")]
  public string? TextColor { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("match")]
  public string? Match { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("matching_algorithm")]
  public MatchingAlgorithm? MatchingAlgorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_insensitive")]
  public bool? IsInsensitive { get; set; }

  /// <summary>
  /// Marks this tag as an inbox tag: All newly consumed documents will be tagged with inbox tags.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_inbox_tag")]
  public bool? IsInboxTag { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("document_count")]
  public int DocumentCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user_can_change")]
  public bool UserCanChange { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("parent")]
  public int? Parent { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("children")]
  public List<int>? Children { get; set; }
}
