//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// TaskStatusCounts from OpenAPI schema.
/// Schema path: #/components/schemas/TaskStatusCounts
/// </summary>
public partial class TaskStatusCounts
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("all")]
  public int All { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("needs_attention")]
  public int NeedsAttention { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("in_progress")]
  public int InProgress { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("completed")]
  public int Completed { get; set; }
}
