//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// Tasks from OpenAPI schema.
/// Schema path: #/components/schemas/Tasks
/// </summary>
public partial class Tasks
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("redis_url")]
  public string? RedisUrl { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("redis_status")]
  public string? RedisStatus { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("redis_error")]
  public string? RedisError { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("celery_status")]
  public string? CeleryStatus { get; set; }
}
