//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// consume_file - Consume File
/// train_classifier - Train Classifier
/// check_sanity - Check Sanity
/// index_optimize - Index Optimize
/// </summary>
public enum TaskNameEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "consume_file")]
    ConsumeFile,

    [EnumMember(Value = "train_classifier")]
    TrainClassifier,

    [EnumMember(Value = "check_sanity")]
    CheckSanity,

    [EnumMember(Value = "index_optimize")]
    IndexOptimize
}
