//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// TaskSummary from OpenAPI schema.
/// Schema path: #/components/schemas/TaskSummary
/// </summary>
public partial class TaskSummary
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("task_type")]
  public string? TaskType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total_count")]
  public int TotalCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pending_count")]
  public int PendingCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("success_count")]
  public int SuccessCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("failure_count")]
  public int FailureCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avg_duration_seconds")]
  public double? AvgDurationSeconds { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avg_wait_time_seconds")]
  public double? AvgWaitTimeSeconds { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("last_run")]
  public DateTimeOffset? LastRun { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("last_success")]
  public DateTimeOffset? LastSuccess { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("last_failure")]
  public DateTimeOffset? LastFailure { get; set; }
}
