//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// consume_file - Consume File
/// train_classifier - Train Classifier
/// sanity_check - Sanity Check
/// index_optimize - Index Optimize
/// mail_fetch - Mail Fetch
/// llm_index - LLM Index
/// empty_trash - Empty Trash
/// check_workflows - Check Workflows
/// bulk_update - Bulk Update
/// reprocess_document - Reprocess Document
/// build_share_link - Build Share Link
/// bulk_delete - Bulk Delete
/// </summary>
public enum TaskTypeEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "consume_file")]
    ConsumeFile,

    [EnumMember(Value = "train_classifier")]
    TrainClassifier,

    [EnumMember(Value = "sanity_check")]
    SanityCheck,

    [EnumMember(Value = "index_optimize")]
    IndexOptimize,

    [EnumMember(Value = "mail_fetch")]
    MailFetch,

    [EnumMember(Value = "llm_index")]
    LlmIndex,

    [EnumMember(Value = "empty_trash")]
    EmptyTrash,

    [EnumMember(Value = "check_workflows")]
    CheckWorkflows,

    [EnumMember(Value = "bulk_update")]
    BulkUpdate,

    [EnumMember(Value = "reprocess_document")]
    ReprocessDocument,

    [EnumMember(Value = "build_share_link")]
    BuildShareLink,

    [EnumMember(Value = "bulk_delete")]
    BulkDelete
}
