//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// TasksViewRequest from OpenAPI schema.
/// Schema path: #/components/schemas/TasksViewRequest
/// </summary>
public class TasksViewRequest
{
  /// <summary>
  /// Celery ID for the Task that was run
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public string? TaskId { get; set; }

  /// <summary>
  /// consume_file - Consume File
  /// train_classifier - Train Classifier
  /// check_sanity - Check Sanity
  /// index_optimize - Index Optimize
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("task_name")]
  public TaskNameEnum? TaskName { get; set; }

  /// <summary>
  /// Name of the file which the Task was run for
  /// </summary>
  [MinLength(1)]
  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonPropertyName("task_file_name")]
  public string? TaskFileName { get; set; }

  /// <summary>
  /// Datetime field when the task result was created in UTC
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date_created")]
  public DateTime? DateCreated { get; set; }

  /// <summary>
  /// Datetime field when the task was completed in UTC
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date_done")]
  public DateTime? DateDone { get; set; }

  /// <summary>
  /// The type of task that was run
  /// 
  /// auto_task - Auto Task
  /// scheduled_task - Scheduled Task
  /// manual_task - Manual Task
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public TasksViewTypeEnum? Type { get; set; }

  /// <summary>
  /// Current state of the task being run
  /// 
  /// FAILURE - FAILURE
  /// PENDING - PENDING
  /// RECEIVED - RECEIVED
  /// RETRY - RETRY
  /// REVOKED - REVOKED
  /// STARTED - STARTED
  /// SUCCESS - SUCCESS
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public StatusEnum? Status { get; set; }

  /// <summary>
  /// The data returned by the task
  /// </summary>
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("result")]
  public string? Result { get; set; }

  /// <summary>
  /// If the task is acknowledged via the frontend or API
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("acknowledged")]
  public bool? Acknowledged { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public int? Owner { get; set; }
}
