//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (10)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// scheduled - Scheduled
/// web_ui - Web UI
/// api_upload - API Upload
/// folder_consume - Folder Consume
/// email_consume - Email Consume
/// system - System
/// manual - Manual
/// </summary>
public enum TriggerSourceEnum
{
    /// <summary>
    /// Unknown or unrecognized value
    /// </summary>
    [EnumMember(Value = "unknown")]
    [Description("Unknown")]
    Unknown = -1,

    [EnumMember(Value = "scheduled")]
    Scheduled,

    [EnumMember(Value = "web_ui")]
    WebUi,

    [EnumMember(Value = "api_upload")]
    ApiUpload,

    [EnumMember(Value = "folder_consume")]
    FolderConsume,

    [EnumMember(Value = "email_consume")]
    EmailConsume,

    [EnumMember(Value = "system")]
    System,

    [EnumMember(Value = "manual")]
    Manual
}
