//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// UiSettingsCreateRequest from OpenAPI schema.
/// Schema path: #/components/schemas/UiSettingsCreateRequest
/// </summary>
public class UiSettingsCreateRequest
{
  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public Dictionary<string, object?>? Settings { get; set; }
}
