//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// WorkflowActionEmailRequest from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowActionEmailRequest
/// </summary>
public class WorkflowActionEmailRequest
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The subject of the email, can include some placeholders, see documentation.
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("subject")]
  public string? Subject { get; set; }

  /// <summary>
  /// The body (message) of the email, can include some placeholders, see documentation.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("body")]
  public string? Body { get; set; }

  /// <summary>
  /// The destination email addresses, comma separated.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("to")]
  public string? To { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("include_document")]
  public bool? IncludeDocument { get; set; }
}
