//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// WorkflowAction from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowAction
/// </summary>
public class WorkflowAction
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public WorkflowActionTypeEnum? Type { get; set; }

  /// <summary>
  /// Assign a document title, can include some placeholders, see documentation.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("assign_title")]
  public string? AssignTitle { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_tags")]
  public List<int?>? AssignTags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_correspondent")]
  public int? AssignCorrespondent { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_document_type")]
  public int? AssignDocumentType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_storage_path")]
  public int? AssignStoragePath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_owner")]
  public int? AssignOwner { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_view_users")]
  public List<int>? AssignViewUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_view_groups")]
  public List<int>? AssignViewGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_change_users")]
  public List<int>? AssignChangeUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_change_groups")]
  public List<int>? AssignChangeGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("assign_custom_fields")]
  public List<int>? AssignCustomFields { get; set; }

  /// <summary>
  /// Optional values to assign to the custom fields.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assign_custom_fields_values")]
  public object? AssignCustomFieldsValues { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_tags")]
  public bool? RemoveAllTags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_tags")]
  public List<int>? RemoveTags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_correspondents")]
  public bool? RemoveAllCorrespondents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_correspondents")]
  public List<int>? RemoveCorrespondents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_document_types")]
  public bool? RemoveAllDocumentTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_document_types")]
  public List<int>? RemoveDocumentTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_storage_paths")]
  public bool? RemoveAllStoragePaths { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_storage_paths")]
  public List<int>? RemoveStoragePaths { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_custom_fields")]
  public List<int>? RemoveCustomFields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_custom_fields")]
  public bool? RemoveAllCustomFields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_owners")]
  public bool? RemoveAllOwners { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_owners")]
  public List<int>? RemoveOwners { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_all_permissions")]
  public bool? RemoveAllPermissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_view_users")]
  public List<int>? RemoveViewUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_view_groups")]
  public List<int>? RemoveViewGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_change_users")]
  public List<int>? RemoveChangeUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remove_change_groups")]
  public List<int>? RemoveChangeGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public WorkflowActionEmail? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webhook")]
  public WorkflowActionWebhook? Webhook { get; set; }
}
