//
// <auto-generated>
// Paperless-ngx API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/paperless-ngx.yaml
// API: Paperless-ngx REST API
// Version: 6.0.0 (9)
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.PaperlessNgx.Models;

/// <summary>
/// WorkflowTriggersPartialUpdateRequest from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowTriggersPartialUpdateRequest
/// </summary>
public class WorkflowTriggersPartialUpdateRequest
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("sources")]
  public List<SourcesEnum>? Sources { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public WorkflowTriggerTypeEnum? Type { get; set; }

  /// <summary>
  /// Only consume documents with a path that matches this if specified. Wildcards specified as * are allowed. Case insensitive.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_path")]
  public string? FilterPath { get; set; }

  /// <summary>
  /// Only consume documents which entirely match this filename if specified. Wildcards such as *.pdf or *invoice* are allowed. Case insensitive.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_filename")]
  public string? FilterFilename { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("filter_mailrule")]
  public int? FilterMailrule { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("matching_algorithm")]
  public WorkflowTriggerMatchingAlgorithmEnum? MatchingAlgorithm { get; set; }

  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("match")]
  public string? Match { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("is_insensitive")]
  public bool? IsInsensitive { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("filter_has_tags")]
  public List<int>? FilterHasTags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("filter_has_correspondent")]
  public int? FilterHasCorrespondent { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("filter_has_document_type")]
  public int? FilterHasDocumentType { get; set; }

  /// <summary>
  /// The number of days to offset the schedule trigger by.
  /// </summary>
  [Range(-2147483648, 2147483647)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("schedule_offset_days")]
  public int? ScheduleOffsetDays { get; set; }

  /// <summary>
  /// If the schedule should be recurring.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("schedule_is_recurring")]
  public bool? ScheduleIsRecurring { get; set; }

  /// <summary>
  /// The number of days between recurring schedule triggers.
  /// </summary>
  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("schedule_recurring_interval_days")]
  public int? ScheduleRecurringIntervalDays { get; set; }

  /// <summary>
  /// The field to check for a schedule trigger.
  /// 
  /// added - Added
  /// created - Created
  /// modified - Modified
  /// custom_field - Custom Field
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("schedule_date_field")]
  public ScheduleDateFieldEnum? ScheduleDateField { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("schedule_date_custom_field")]
  public int? ScheduleDateCustomField { get; set; }
}
